module.exports ={
    getclassifyInfo() {
        let classifyInfo = {
            "vheader": {
                "vinput": "搜索商品/店铺/种类"
            },
            "text":{
               "font":"榜单"
            },
            "content":{
                "lefts":[
                    {"text":"图书"} ,
                    {"text":"童书"} ,
                    {"text":"电子书"} ,
                    {"text":"听书"} ,
                    {"text":"网络文学"} ,
                    {"text":"创意文具"} ,
                    {"text":"旧书/拍卖"} ,
                    {"text":"女装"} ,
                    {"text":"男装"} ,
                    {"text":"男女鞋"} ,
                    {"text":"童装童鞋"} ,
                    {"text":"内衣配饰"} ,
                    {"text":"母婴玩具"} ,
                    {"text":"食品生鲜"} ,
                    {"text":"美妆个护"} ,
                    {"text":"手机数码"} ,
                    {"text":"母婴玩具"} ,
                    {"text":"男女鞋"} ,
                    {"text":"创意文具"} ,
                    {"text":"网络文学"}
                ],
                "rights":[
                    {
                    "squres":[
                        {
                            "divs":"进入当当书城",
                            "ps":"特价地址1.9折"
                        },
                        {
                            "divs":"进入童书观",
                            "ps":"精选少儿读物"
                        }
                    ],
                    "fristlists":[
                        {
                            "pic":"http://59.110.229.146/images/imgs2/tu-1568871813.png",
                            "ps":"总榜"
                        },
                        {
                            "pic":"http://59.110.229.146/images/imgs2/new-1570687132.png",
                            "ps":"新书榜"
                        },
                        {
                            "pic":"http://59.110.229.146/images/imgs2/kid-1565680692.png",
                            "ps":"童书榜"
                        }
                    ],
                    "authors":[
                        {
                            "text1":"小说",
                            "text2":"畅销榜",
                            "text3":"社会",
                            "text4":"侦探/悬疑/推理",
                            "text5":"情感",
                            "text6":"世界名著",
                            "text7":"历史",
                            "text8":"展开"
                        },
                        {
                            "text1":"文学",
                            "text2":"畅销榜",
                            "text3":"中国现代随笔",
                            "text4":"名家作品",
                            "text5":"文集",
                            "text6":"纪实文学",
                            "text7":"中国古诗词",
                            "text8":"展开"
                        },
                        {
                            "text1":"小说",
                            "text2":"畅销榜",
                            "text3":"社会",
                            "text4":"侦探/悬疑/推理",
                            "text5":"情感",
                            "text6":"世界名著",
                            "text7":"历史",
                            "text8":"展开"
                        }
                    ]
                },
                    {
                        "squres":[
                            {
                                "divs":"进入公共书城",
                                "ps":"特价地址2.6折"
                            },
                            {
                                "divs":"进入孔书观",
                                "ps":"精选青年读物"
                            }
                        ],
                        "fristlists":[
                            {
                                "pic":"http://59.110.229.146/images/imgs2/tu-1568871813.png",
                                "ps":"总榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/new-1570687132.png",
                                "ps":"新书榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/kid-1565680692.png",
                                "ps":"童书榜"
                            }
                        ],
                        "authors":[
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            },
                            {
                                "text1":"文学",
                                "text2":"畅销榜",
                                "text3":"中国现代随笔",
                                "text4":"名家作品",
                                "text5":"文集",
                                "text6":"纪实文学",
                                "text7":"中国古诗词",
                                "text8":"展开"
                            },
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            }
                        ]
                    },
                    {
                        "squres":[
                            {
                                "divs":"进入当当书城",
                                "ps":"特价地址1.9折"
                            },
                            {
                                "divs":"进入童书观",
                                "ps":"精选少儿读物"
                            }
                        ],
                        "fristlists":[
                            {
                                "pic":"http://59.110.229.146/images/imgs2/tu-1568871813.png",
                                "ps":"总榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/new-1570687132.png",
                                "ps":"新书榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/kid-1565680692.png",
                                "ps":"童书榜"
                            }
                        ],
                        "authors":[
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            },
                            {
                                "text1":"文学",
                                "text2":"畅销榜",
                                "text3":"中国现代随笔",
                                "text4":"名家作品",
                                "text5":"文集",
                                "text6":"纪实文学",
                                "text7":"中国古诗词",
                                "text8":"展开"
                            },
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            }
                        ]
                    },
                    {
                        "squres":[
                            {
                                "divs":"进入公共书城",
                                "ps":"特价地址2.6折"
                            },
                            {
                                "divs":"进入孔书观",
                                "ps":"精选青年读物"
                            }
                        ],
                        "fristlists":[
                            {
                                "pic":"http://59.110.229.146/images/imgs2/tu-1568871813.png",
                                "ps":"总榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/new-1570687132.png",
                                "ps":"新书榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/kid-1565680692.png",
                                "ps":"童书榜"
                            }
                        ],
                        "authors":[
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            },
                            {
                                "text1":"文学",
                                "text2":"畅销榜",
                                "text3":"中国现代随笔",
                                "text4":"名家作品",
                                "text5":"文集",
                                "text6":"纪实文学",
                                "text7":"中国古诗词",
                                "text8":"展开"
                            },
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            }
                        ]
                    },
                    {
                        "squres":[
                            {
                                "divs":"进入当当书城",
                                "ps":"特价地址1.9折"
                            },
                            {
                                "divs":"进入童书观",
                                "ps":"精选少儿读物"
                            }
                        ],
                        "fristlists":[
                            {
                                "pic":"http://59.110.229.146/images/imgs2/tu-1568871813.png",
                                "ps":"总榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/new-1570687132.png",
                                "ps":"新书榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/kid-1565680692.png",
                                "ps":"童书榜"
                            }
                        ],
                        "authors":[
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            },
                            {
                                "text1":"文学",
                                "text2":"畅销榜",
                                "text3":"中国现代随笔",
                                "text4":"名家作品",
                                "text5":"文集",
                                "text6":"纪实文学",
                                "text7":"中国古诗词",
                                "text8":"展开"
                            },
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            }
                        ]
                    },
                    {
                        "squres":[
                            {
                                "divs":"进入公共书城",
                                "ps":"特价地址2.6折"
                            },
                            {
                                "divs":"进入孔书观",
                                "ps":"精选青年读物"
                            }
                        ],
                        "fristlists":[
                            {
                                "pic":"http://59.110.229.146/images/imgs2/tu-1568871813.png",
                                "ps":"总榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/new-1570687132.png",
                                "ps":"新书榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/kid-1565680692.png",
                                "ps":"童书榜"
                            }
                        ],
                        "authors":[
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            },
                            {
                                "text1":"文学",
                                "text2":"畅销榜",
                                "text3":"中国现代随笔",
                                "text4":"名家作品",
                                "text5":"文集",
                                "text6":"纪实文学",
                                "text7":"中国古诗词",
                                "text8":"展开"
                            },
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            }
                        ]
                    },
                    {
                        "squres":[
                            {
                                "divs":"进入当当书城",
                                "ps":"特价地址1.9折"
                            },
                            {
                                "divs":"进入童书观",
                                "ps":"精选少儿读物"
                            }
                        ],
                        "fristlists":[
                            {
                                "pic":"http://59.110.229.146/images/imgs2/tu-1568871813.png",
                                "ps":"总榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/new-1570687132.png",
                                "ps":"新书榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/kid-1565680692.png",
                                "ps":"童书榜"
                            }
                        ],
                        "authors":[
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            },
                            {
                                "text1":"文学",
                                "text2":"畅销榜",
                                "text3":"中国现代随笔",
                                "text4":"名家作品",
                                "text5":"文集",
                                "text6":"纪实文学",
                                "text7":"中国古诗词",
                                "text8":"展开"
                            },
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            }
                        ]
                    },
                    {
                        "squres":[
                            {
                                "divs":"进入公共书城",
                                "ps":"特价地址2.6折"
                            },
                            {
                                "divs":"进入孔书观",
                                "ps":"精选青年读物"
                            }
                        ],
                        "fristlists":[
                            {
                                "pic":"http://59.110.229.146/images/imgs2/tu-1568871813.png",
                                "ps":"总榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/new-1570687132.png",
                                "ps":"新书榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/kid-1565680692.png",
                                "ps":"童书榜"
                            }
                        ],
                        "authors":[
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            },
                            {
                                "text1":"文学",
                                "text2":"畅销榜",
                                "text3":"中国现代随笔",
                                "text4":"名家作品",
                                "text5":"文集",
                                "text6":"纪实文学",
                                "text7":"中国古诗词",
                                "text8":"展开"
                            },
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            }
                        ]
                    },
                    {
                        "squres":[
                            {
                                "divs":"进入当当书城",
                                "ps":"特价地址1.9折"
                            },
                            {
                                "divs":"进入童书观",
                                "ps":"精选少儿读物"
                            }
                        ],
                        "fristlists":[
                            {
                                "pic":"http://59.110.229.146/images/imgs2/tu-1568871813.png",
                                "ps":"总榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/new-1570687132.png",
                                "ps":"新书榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/kid-1565680692.png",
                                "ps":"童书榜"
                            }
                        ],
                        "authors":[
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            },
                            {
                                "text1":"文学",
                                "text2":"畅销榜",
                                "text3":"中国现代随笔",
                                "text4":"名家作品",
                                "text5":"文集",
                                "text6":"纪实文学",
                                "text7":"中国古诗词",
                                "text8":"展开"
                            },
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            }
                        ]
                    },
                    {
                        "squres":[
                            {
                                "divs":"进入公共书城",
                                "ps":"特价地址2.6折"
                            },
                            {
                                "divs":"进入孔书观",
                                "ps":"精选青年读物"
                            }
                        ],
                        "fristlists":[
                            {
                                "pic":"http://59.110.229.146/images/imgs2/tu-1568871813.png",
                                "ps":"总榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/new-1570687132.png",
                                "ps":"新书榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/kid-1565680692.png",
                                "ps":"童书榜"
                            }
                        ],
                        "authors":[
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            },
                            {
                                "text1":"文学",
                                "text2":"畅销榜",
                                "text3":"中国现代随笔",
                                "text4":"名家作品",
                                "text5":"文集",
                                "text6":"纪实文学",
                                "text7":"中国古诗词",
                                "text8":"展开"
                            },
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            }
                        ]
                    },
                    {
                        "squres":[
                            {
                                "divs":"进入当当书城",
                                "ps":"特价地址1.9折"
                            },
                            {
                                "divs":"进入童书观",
                                "ps":"精选少儿读物"
                            }
                        ],
                        "fristlists":[
                            {
                                "pic":"http://59.110.229.146/images/imgs2/tu-1568871813.png",
                                "ps":"总榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/new-1570687132.png",
                                "ps":"新书榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/kid-1565680692.png",
                                "ps":"童书榜"
                            }
                        ],
                        "authors":[
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            },
                            {
                                "text1":"文学",
                                "text2":"畅销榜",
                                "text3":"中国现代随笔",
                                "text4":"名家作品",
                                "text5":"文集",
                                "text6":"纪实文学",
                                "text7":"中国古诗词",
                                "text8":"展开"
                            },
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            }
                        ]
                    },
                    {
                        "squres":[
                            {
                                "divs":"进入公共书城",
                                "ps":"特价地址2.6折"
                            },
                            {
                                "divs":"进入孔书观",
                                "ps":"精选青年读物"
                            }
                        ],
                        "fristlists":[
                            {
                                "pic":"http://59.110.229.146/images/imgs2/tu-1568871813.png",
                                "ps":"总榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/new-1570687132.png",
                                "ps":"新书榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/kid-1565680692.png",
                                "ps":"童书榜"
                            }
                        ],
                        "authors":[
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            },
                            {
                                "text1":"文学",
                                "text2":"畅销榜",
                                "text3":"中国现代随笔",
                                "text4":"名家作品",
                                "text5":"文集",
                                "text6":"纪实文学",
                                "text7":"中国古诗词",
                                "text8":"展开"
                            },
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            }
                        ]
                    },
                    {
                        "squres":[
                            {
                                "divs":"进入当当书城",
                                "ps":"特价地址1.9折"
                            },
                            {
                                "divs":"进入童书观",
                                "ps":"精选少儿读物"
                            }
                        ],
                        "fristlists":[
                            {
                                "pic":"http://59.110.229.146/images/imgs2/tu-1568871813.png",
                                "ps":"总榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/new-1570687132.png",
                                "ps":"新书榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/kid-1565680692.png",
                                "ps":"童书榜"
                            }
                        ],
                        "authors":[
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            },
                            {
                                "text1":"文学",
                                "text2":"畅销榜",
                                "text3":"中国现代随笔",
                                "text4":"名家作品",
                                "text5":"文集",
                                "text6":"纪实文学",
                                "text7":"中国古诗词",
                                "text8":"展开"
                            },
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            }
                        ]
                    },
                    {
                        "squres":[
                            {
                                "divs":"进入公共书城",
                                "ps":"特价地址2.6折"
                            },
                            {
                                "divs":"进入孔书观",
                                "ps":"精选青年读物"
                            }
                        ],
                        "fristlists":[
                            {
                                "pic":"http://59.110.229.146/images/imgs2/tu-1568871813.png",
                                "ps":"总榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/new-1570687132.png",
                                "ps":"新书榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/kid-1565680692.png",
                                "ps":"童书榜"
                            }
                        ],
                        "authors":[
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            },
                            {
                                "text1":"文学",
                                "text2":"畅销榜",
                                "text3":"中国现代随笔",
                                "text4":"名家作品",
                                "text5":"文集",
                                "text6":"纪实文学",
                                "text7":"中国古诗词",
                                "text8":"展开"
                            },
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            }
                        ]
                    },
                    {
                        "squres":[
                            {
                                "divs":"进入当当书城",
                                "ps":"特价地址1.9折"
                            },
                            {
                                "divs":"进入童书观",
                                "ps":"精选少儿读物"
                            }
                        ],
                        "fristlists":[
                            {
                                "pic":"http://59.110.229.146/images/imgs2/tu-1568871813.png",
                                "ps":"总榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/new-1570687132.png",
                                "ps":"新书榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/kid-1565680692.png",
                                "ps":"童书榜"
                            }
                        ],
                        "authors":[
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            },
                            {
                                "text1":"文学",
                                "text2":"畅销榜",
                                "text3":"中国现代随笔",
                                "text4":"名家作品",
                                "text5":"文集",
                                "text6":"纪实文学",
                                "text7":"中国古诗词",
                                "text8":"展开"
                            },
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            }
                        ]
                    },
                    {
                        "squres":[
                            {
                                "divs":"进入公共书城",
                                "ps":"特价地址2.6折"
                            },
                            {
                                "divs":"进入孔书观",
                                "ps":"精选青年读物"
                            }
                        ],
                        "fristlists":[
                            {
                                "pic":"http://59.110.229.146/images/imgs2/tu-1568871813.png",
                                "ps":"总榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/new-1570687132.png",
                                "ps":"新书榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/kid-1565680692.png",
                                "ps":"童书榜"
                            }
                        ],
                        "authors":[
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            },
                            {
                                "text1":"文学",
                                "text2":"畅销榜",
                                "text3":"中国现代随笔",
                                "text4":"名家作品",
                                "text5":"文集",
                                "text6":"纪实文学",
                                "text7":"中国古诗词",
                                "text8":"展开"
                            },
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            }
                        ]
                    },
                    {
                        "squres":[
                            {
                                "divs":"进入当当书城",
                                "ps":"特价地址1.9折"
                            },
                            {
                                "divs":"进入童书观",
                                "ps":"精选少儿读物"
                            }
                        ],
                        "fristlists":[
                            {
                                "pic":"http://59.110.229.146/images/imgs2/tu-1568871813.png",
                                "ps":"总榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/new-1570687132.png",
                                "ps":"新书榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/kid-1565680692.png",
                                "ps":"童书榜"
                            }
                        ],
                        "authors":[
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            },
                            {
                                "text1":"文学",
                                "text2":"畅销榜",
                                "text3":"中国现代随笔",
                                "text4":"名家作品",
                                "text5":"文集",
                                "text6":"纪实文学",
                                "text7":"中国古诗词",
                                "text8":"展开"
                            },
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            }
                        ]
                    },
                    {
                        "squres":[
                            {
                                "divs":"进入当当书城",
                                "ps":"特价地址1.9折"
                            },
                            {
                                "divs":"进入童书观",
                                "ps":"精选少儿读物"
                            }
                        ],
                        "fristlists":[
                            {
                                "pic":"http://59.110.229.146/images/imgs2/tu-1568871813.png",
                                "ps":"总榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/new-1570687132.png",
                                "ps":"新书榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/kid-1565680692.png",
                                "ps":"童书榜"
                            }
                        ],
                        "authors":[
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            },
                            {
                                "text1":"文学",
                                "text2":"畅销榜",
                                "text3":"中国现代随笔",
                                "text4":"名家作品",
                                "text5":"文集",
                                "text6":"纪实文学",
                                "text7":"中国古诗词",
                                "text8":"展开"
                            },
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            }
                        ]
                    },
                    {
                        "squres":[
                            {
                                "divs":"进入公共书城",
                                "ps":"特价地址2.6折"
                            },
                            {
                                "divs":"进入孔书观",
                                "ps":"精选青年读物"
                            }
                        ],
                        "fristlists":[
                            {
                                "pic":"http://59.110.229.146/images/imgs2/tu-1568871813.png",
                                "ps":"总榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/new-1570687132.png",
                                "ps":"新书榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/kid-1565680692.png",
                                "ps":"童书榜"
                            }
                        ],
                        "authors":[
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            },
                            {
                                "text1":"文学",
                                "text2":"畅销榜",
                                "text3":"中国现代随笔",
                                "text4":"名家作品",
                                "text5":"文集",
                                "text6":"纪实文学",
                                "text7":"中国古诗词",
                                "text8":"展开"
                            },
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            }
                        ]
                    },
                    {
                        "squres":[
                            {
                                "divs":"进入公共书城",
                                "ps":"特价地址2.6折"
                            },
                            {
                                "divs":"进入孔书观",
                                "ps":"精选青年读物"
                            }
                        ],
                        "fristlists":[
                            {
                                "pic":"http://59.110.229.146/images/imgs2/tu-1568871813.png",
                                "ps":"总榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/new-1570687132.png",
                                "ps":"新书榜"
                            },
                            {
                                "pic":"http://59.110.229.146/images/imgs2/kid-1565680692.png",
                                "ps":"童书榜"
                            }
                        ],
                        "authors":[
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            },
                            {
                                "text1":"文学",
                                "text2":"畅销榜",
                                "text3":"中国现代随笔",
                                "text4":"名家作品",
                                "text5":"文集",
                                "text6":"纪实文学",
                                "text7":"中国古诗词",
                                "text8":"展开"
                            },
                            {
                                "text1":"小说",
                                "text2":"畅销榜",
                                "text3":"社会",
                                "text4":"侦探/悬疑/推理",
                                "text5":"情感",
                                "text6":"世界名著",
                                "text7":"历史",
                                "text8":"展开"
                            }
                        ]
                    }
                ]
            }
        };
        return classifyInfo
    }
};